export const CHANGE_OFFSET = 'APP/CHANGE_OFFSET'
export const SET_OFFSET = 'APP/SET_OFFSET'
export const SET_MESSAGE = 'APP/SET_MESSAGE'
export const SET_PERMANENT_MESSAGE = 'APP/SET_PERMANENT_MESSAGE'