name: study-actions
env:
  APPLICATION_NAME: "time-organizer"
  DEPLOY_PACKAGE_NAME: "time-organizer-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-20.04

    steps:
      - name: Print Hello message
        run: echo "Hello World from testing"

      - name: List current folder
        run: ls -la

      - name: Git clone my repo
        uses: actions/checkout@v1
      
      - name: List current folder
        run: ls -la
  
  my_deploy:
    runs-on: ubuntu-20.04
    needs: [my_testing]

    steps:
      - name: Print Deploy Package Name
        run: echo "Package Name is ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Check aws cli
        run: aws --version

      - name: Check zip
        run: zip --version
